
POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Event A",
    "details": "A concert featuring the band The Beatles",
    "maxAttendees": 100
}

###

POST http://localhost:3333/events/d97443ca-71ff-4e22-93b0-2c0fe0981b51/attendees
Content-Type: application/json

{
    "name": "john12",
    "email": "john12@test.com"
}


###

GET http://localhost:3333/events/d97443ca-71ff-4e22-93b0-2c0fe0981b51

###

GET http://localhost:3333/attendees/9/badge

###

GET http://localhost:3333/attendees/9/check-in

###

GET http://localhost:3333/events/d97443ca-71ff-4e22-93b0-2c0fe0981b51/attendees

###

GET http://localhost:3333/events/d97443ca-71ff-4e22-93b0-2c0fe0981b51/attendees?page_index=0
