POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Testt",
    "details": "A concert featuring the band The Beatles",
    "maxAttendees": 100
}

###

POST http://localhost:3333/events/f36cbf54-1432-4120-8952-8f8c601bed2a/attendees
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@test.com"
}


###

GET http://localhost:3333/events/f36cbf54-1432-4120-8952-8f8c601bed2a

###

GET http://localhost:3333/attendees/3/badge

